name: Deploy docuvet-api dev
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - dev
jobs:
  DeployInfrastructure:
    runs-on: buildjet-4vcpu-ubuntu-2204
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials with GitHub-AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}

      - uses: actions/setup-node@v4
        with:
          check-latest: true

      - run: npm install -g aws-cdk

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.dev.txt
      - run: pip install -r requirements.txt
      - run: doppler run -- pytest
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service docuvet-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
