name: Deploy docuvet-api prod
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - master
jobs:
  DeployInfrastructure:
    runs-on: buildjet-4vcpu-ubuntu-2204
    environment: prd
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          check-latest: true

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up --service video-clipper-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
